
apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: meportal
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJtZXBvcnRhbDEyMzQuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImFtWnliMmRrYjJOclpYSmpjbVZrT2s1aGFXdHdjbUZrZVhWdGJtRkFOREF3TXpBPSIKCQl9LAoJCSJteXBvcnRhbGwxMjM0Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJhbVp5YjJka2IyTnJaWEpqY21Wa09rNWhhV3R3Y21GNlFFQXlPVFU9IgoJCX0KCX0KfQ==

type: kubernetes.io/dockerconfigjson
